nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*'] # Permet les requêtes de n'importe quelle origine
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Access-Control-Request-Method', 'Access-Control-Request-Headers']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # Applique cette configuration spécifiquement aux routes commençant par /api/
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Access-Control-Request-Method', 'Access-Control-Request-Headers']
            expose_headers: ['Link']
            max_age: 3600
            allow_credentials: true
