# services.yaml
parameters:
  profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
